import type { LearningSummary } from '@everecho/contracts';
import type { Transaction } from '@everecho/db';

/**
 * What the storyteller is shown when a conversation ends.
 *
 * Counts and unresolved references only. Deliberately contains **no memory
 * content**: this text ends up in a notification, an email subject, and an
 * operational view, and every one of those is somewhere memory content must
 * never appear.
 */
export async function summariseSession(
  tx: Transaction,
  input: { archiveId: string; sessionId: string },
): Promise<LearningSummary | null> {
  const counts = await tx.maybeOne<{
    total: string;
    needs_review: string;
    duplicates: string;
    contradictions: string;
  }>(
    `SELECT count(*) AS total,
            count(*) FILTER (WHERE requires_storyteller_review) AS needs_review,
            count(*) FILTER (WHERE duplicate_of_memory_id IS NOT NULL
                                OR duplicate_of_candidate_id IS NOT NULL) AS duplicates,
            count(*) FILTER (WHERE cardinality(contradicts_memory_ids) > 0) AS contradictions
       FROM memory_candidate
      WHERE archive_id = $1 AND session_id = $2 AND deleted_at IS NULL`,
    [input.archiveId, input.sessionId],
  );
  if (!counts) return null;

  const unresolved = await tx.query<{ title: string }>(
    `SELECT title FROM memory_candidate
      WHERE archive_id = $1 AND session_id = $2 AND kind = 'unresolved_reference'
        AND status = 'pending' AND deleted_at IS NULL
      ORDER BY created_at ASC
      LIMIT 10`,
    [input.archiveId, input.sessionId],
  );

  const total = Number(counts.total);
  const needsReview = Number(counts.needs_review);

  return {
    sessionId: input.sessionId,
    candidateCount: total,
    requiresReviewCount: needsReview,
    duplicateCount: Number(counts.duplicates),
    contradictionCount: Number(counts.contradictions),
    autoSavedPreferenceKeys: [],
    // The titles of unresolved-reference candidates are generated by us and
    // name only the pronoun that was left dangling, never what was said about it.
    unresolvedReferences: unresolved.map((u) => u.title.replace(/^Unresolved:\s*/, '')),
    headline: headline(total, needsReview),
  };
}

function headline(total: number, needsReview: number): string {
  if (total === 0) {
    return 'Nothing was suggested from this conversation.';
  }
  if (needsReview === 0) {
    return `${total} suggestion${total === 1 ? '' : 's'} from this conversation.`;
  }
  return (
    `${total} suggestion${total === 1 ? '' : 's'} from this conversation, ` +
    `${needsReview} waiting for you to decide.`
  );
}
